# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=100.0)),
            ],
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.PositiveIntegerField()),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid', models.PositiveIntegerField(default=10)),
                ('pair', models.CharField(choices=[('EUR/USD', 'EUR/USD'), ('USD/EUR', 'USD/EUR')], max_length=100)),
                ('operation', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=100)),
                ('status', models.CharField(choices=[('fail', 'Fail'), ('success', 'Success'), ('in_progress', 'In progress')], default='in_progress', max_length=100)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.Bot')),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='bot',
            name='signals',
            field=models.ManyToManyField(related_name='bots', to='api.Signal'),
        ),
        migrations.AddField(
            model_name='bot',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot', to='api.BotUser'),
        ),
    ]
