# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='ios_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='chat_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
