# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170423_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='with_etf',
            field=models.BooleanField(default=False),
        ),
    ]
